version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.external
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DB_TYPE=${DB_TYPE}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@db:${DB_PORT}/${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    volumes:
      - ../data/media:/app/data/media
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    # Uncomment below for MySQL alternative
    # image: mysql:8
    # environment:
    #   MYSQL_ROOT_PASSWORD: ${DB_PASS}
    #   MYSQL_DATABASE: ${DB_NAME}
    #   MYSQL_USER: ${DB_USER}
    #   MYSQL_PASSWORD: ${DB_PASS}
    # ports:
    #   - "3306:3306"